--TABELA CLIENTE
CREATE TABLE TBLCLI (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	cpf VARCHAR(20),
	cnpj VARCHAR(30),
	data_nascimento DATE,
	ativo BOOLEAN,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(id)
);

--TABELA PRODUTO CATEGORIA
CREATE TABLE TBLPROCAT (
	id INTEGER NOT NULL,
	categoria VARCHAR(50),
	CONSTRAINT PK_PRODUTOCATEGORIA PRIMARY KEY(id)
);

--TABELA PRODUTO
CREATE TABLE TBLPRO (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	descricao VARCHAR(255),
	quantidade INTEGER,
	preco_custo DOUBLE PRECISION,
	preco_venda DOUBLE PRECISION,
	id_categoria INTEGER,
	ativo BOOLEAN,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(id),
	CONSTRAINT FK_PRODUTOCATEGORIA FOREIGN KEY(id_categoria) REFERENCES TBLPROCAT(id)
);

--TABELA USUARIOS PERFIL
CREATE TABLE TBLUSUPER (
	id INTEGER NOT NULL,
	perfil VARCHAR(20),
	CONSTRAINT PK_USUARIOPERFIL PRIMARY KEY(id)
);

--TABELA USUARIOS
CREATE TABLE TBLUSU (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	matricula VARCHAR(20),
	data_contratacao DATE,
	id_perfil INTEGER,
	ativo BOOLEAN,
	CONSTRAINT PK_USUARIO PRIMARY KEY(id),
	CONSTRAINT FK_USUARIOPERFIL FOREIGN KEY(id_perfil) REFERENCES TBLUSUPER(id)
);

--TABELA VENDAS
CREATE TABLE TBLVEN (
	id INTEGER NOT NULL,
	id_cliente INTEGER,
	id_usuario INTEGER,
	id_produto INTEGER,
	CONSTRAINT PK_VENDA PRIMARY KEY(id),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(id_cliente) REFERENCES TBLCLI(id),
	CONSTRAINT FK_USUARIO FOREIGN KEY(id_usuario) REFERENCES TBLUSU(id),
	CONSTRAINT FK_PRODUTO FOREIGN KEY(id_produto) REFERENCES TBLPRO(id)
);

--DOMINIO PRIMARY KEY
CREATE DOMAIN DMN_PRIMARY_KEY INTEGER NOT NULL;

--DOMINIO DESCRICAO
CREATE DOMAIN DMN_DESCRICAO_100 VARCHAR(100);

--ALTER TABLE PARA COLOCAR OS DOMINIOS
ALTER TABLE TBLVEN DROP CONSTRAINT PK_VENDA,
DROP CONSTRAINT FK_CLIENTE,
DROP CONSTRAINT FK_PRODUTO,
DROP CONSTRAINT FK_USUARIO;

ALTER TABLE TBLVEN ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_VENDA PRIMARY KEY(id);

ALTER TABLE TBLCLI DROP CONSTRAINT PK_CLIENTE;

ALTER TABLE TBLCLI ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100;

ALTER TABLE TBLPRO DROP CONSTRAINT PK_PRODUTO; 

ALTER TABLE TBLPRO ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100,
DROP CONSTRAINT FK_PRODUTOCATEGORIA;

ALTER TABLE TBLPROCAT DROP CONSTRAINT PK_PRODUTOCATEGORIA;

ALTER TABLE TBLPROCAT ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_PRODUTOCATEGORIA PRIMARY KEY(id);

ALTER TABLE TBLUSU DROP CONSTRAINT PK_USUARIO;

ALTER TABLE TBLUSU ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_USUARIO PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100,
DROP CONSTRAINT FK_USUARIOPERFIL;

ALTER TABLE TBLUSUPER DROP CONSTRAINT PK_USUARIOPERFIL;

ALTER TABLE TBLUSUPER ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_USUARIOPERFIL PRIMARY KEY(id);

ALTER TABLE TBLVEN 
ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(id_cliente) REFERENCES TBLCLI(id),
ADD CONSTRAINT FK_USUARIO FOREIGN KEY(id_usuario) REFERENCES TBLUSU(id),
ADD CONSTRAINT FK_PRODUTO FOREIGN KEY(id_produto) REFERENCES TBLPRO(id);

ALTER TABLE TBLPRO 
ADD CONSTRAINT FK_PRODUTOCATEGORIA FOREIGN KEY(id_categoria) REFERENCES TBLPROCAT(id);

ALTER TABLE TBLUSU 
ADD CONSTRAINT FK_USUARIOPERFIL FOREIGN KEY(id_perfil) REFERENCES TBLUSUPER(id);
