--TABELA CLIENTE
CREATE TABLE TBLCLI (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	cpf VARCHAR(20) NOT NULL,
	cnpj VARCHAR(30) NOT NULL,
	data_nascimento DATE,
	ativo BOOLEAN,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(id)
);

--TABELA PRODUTO CATEGORIA
CREATE TABLE TBLPROCAT (
	id INTEGER NOT NULL,
	categoria VARCHAR(50),
	CONSTRAINT PK_PRODUTOCATEGORIA PRIMARY KEY(id)
);

--TABELA PRODUTO
CREATE TABLE TBLPRO (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	descricao VARCHAR(255),
	quantidade INTEGER,
	preco_custo DOUBLE PRECISION,
	preco_venda DOUBLE PRECISION,
	id_categoria INTEGER,
	ativo BOOLEAN,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(id),
	CONSTRAINT FK_PRODUTOCATEGORIA FOREIGN KEY(id_categoria) REFERENCES TBLPROCAT(id)
);

--TABELA USUARIOS PERFIL
CREATE TABLE TBLUSUPER (
	id INTEGER NOT NULL,
	perfil VARCHAR(20),
	CONSTRAINT PK_USUARIOPERFIL PRIMARY KEY(id)
);

--TABELA USUARIOS
CREATE TABLE TBLUSU (
	id INTEGER NOT NULL,
	nome VARCHAR(100),
	matricula VARCHAR(20),
	data_contratacao DATE,
	id_perfil INTEGER,
	ativo BOOLEAN,
	CONSTRAINT PK_USUARIO PRIMARY KEY(id),
	CONSTRAINT FK_USUARIOPERFIL FOREIGN KEY(id_perfil) REFERENCES TBLUSUPER(id)
);

--TABELA VENDAS
CREATE TABLE TBLVEN (
	id INTEGER NOT NULL,
	id_cliente INTEGER,
	cpf_cliente VARCHAR(20),
	cnpj_cliente VARCHAR(30),
	id_usuario INTEGER,
	id_produto INTEGER,
	quantidade_produtos INTEGER,
	valor_total DOUBLE PRECISION,
	desconto DOUBLE PRECISION,
	forma_pagamento VARCHAR(30),
	data_venda DATE,
	hora_venda TIME,
	CONSTRAINT PK_VENDA PRIMARY KEY(id),
	CONSTRAINT FK_CLIENTEVENDA FOREIGN KEY(id_cliente) REFERENCES TBLCLI(id),
	CONSTRAINT FK_USUARIOVENDA FOREIGN KEY(id_usuario) REFERENCES TBLUSU(id),
	CONSTRAINT FK_PRODUTOVENDA FOREIGN KEY(id_produto) REFERENCES TBLPRO(id)
);

--TABELA FORNECEDOR
CREATE TABLE TBLFOR (
	id INTEGER NOT NULL,
	razao VARCHAR(100),
	cnpj VARCHAR(30) NOT NULL,
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY(id)
);

--TABELA COMPRAS
CREATE TABLE TBLCOM (
	id INTEGER NOT NULL,
	id_fornecedor INTEGER,
	cnpj_fornecedor VARCHAR(30),
	id_produto INTEGER,
	quantidade_produtos INTEGER,
	valor_total DOUBLE PRECISION,
	forma_pagamento VARCHAR(30),
	data_compra DATE,
	hora_compra TIME,
	CONSTRAINT PK_COMPRA PRIMARY KEY(id),
	CONSTRAINT FK_FORNECEDORCOMPRA FOREIGN KEY(id_fornecedor) REFERENCES TBLFOR(id),
	CONSTRAINT FK_PRODUTOCOMPRA FOREIGN KEY(id_produto) REFERENCES TBLPRO(id)
);

--DOMINIO PRIMARY KEY
CREATE DOMAIN DMN_PRIMARY_KEY INTEGER NOT NULL;

--DOMINIO DESCRICAO
CREATE DOMAIN DMN_DESCRICAO_100 VARCHAR(100);

--ALTER TABLE PARA COLOCAR OS DOMINIOS
ALTER TABLE TBLVEN DROP CONSTRAINT PK_VENDA;

ALTER TABLE TBLVEN ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_VENDA PRIMARY KEY(id),
DROP CONSTRAINT FK_CLIENTEVENDA,
DROP CONSTRAINT FK_PRODUTOVENDA,
DROP CONSTRAINT FK_USUARIOVENDA;

ALTER TABLE TBLCOM DROP CONSTRAINT PK_COMPRA;

ALTER TABLE TBLCOM ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_COMPRA PRIMARY KEY(id),
DROP CONSTRAINT FK_FORNECEDORCOMPRA,
DROP CONSTRAINT FK_PRODUTOCOMPRA;

ALTER TABLE TBLCLI DROP CONSTRAINT PK_CLIENTE;

ALTER TABLE TBLCLI ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100;

ALTER TABLE TBLPRO DROP CONSTRAINT PK_PRODUTO; 

ALTER TABLE TBLPRO ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100,
DROP CONSTRAINT FK_PRODUTOCATEGORIA;

ALTER TABLE TBLPROCAT DROP CONSTRAINT PK_PRODUTOCATEGORIA;

ALTER TABLE TBLPROCAT ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_PRODUTOCATEGORIA PRIMARY KEY(id);

ALTER TABLE TBLUSU DROP CONSTRAINT PK_USUARIO;

ALTER TABLE TBLUSU ALTER COLUMN id TYPE DMN_PRIMARY_KEY, 
ADD CONSTRAINT PK_USUARIO PRIMARY KEY(id), 
ALTER COLUMN nome TYPE DMN_DESCRICAO_100,
DROP CONSTRAINT FK_USUARIOPERFIL;

ALTER TABLE TBLUSUPER DROP CONSTRAINT PK_USUARIOPERFIL;

ALTER TABLE TBLUSUPER ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_USUARIOPERFIL PRIMARY KEY(id);

ALTER TABLE TBLFOR DROP CONSTRAINT PK_FORNECEDOR;

ALTER TABLE TBLFOR ALTER COLUMN id TYPE DMN_PRIMARY_KEY,
ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY(id);

ALTER TABLE TBLCOM 
ADD CONSTRAINT FK_FORNECEDORCOMPRA FOREIGN KEY(id_fornecedor) REFERENCES TBLFOR(id),
ADD CONSTRAINT FK_PRODUTOCOMPRA FOREIGN KEY(id_produto) REFERENCES TBLPRO(id);

ALTER TABLE TBLVEN 
ADD CONSTRAINT FK_CLIENTEVENDA FOREIGN KEY(id_cliente) REFERENCES TBLCLI(id),
ADD CONSTRAINT FK_USUARIOVENDA FOREIGN KEY(id_usuario) REFERENCES TBLUSU(id),
ADD CONSTRAINT FK_PRODUTOVENDA FOREIGN KEY(id_produto) REFERENCES TBLPRO(id);

ALTER TABLE TBLPRO 
ADD CONSTRAINT FK_PRODUTOCATEGORIA FOREIGN KEY(id_categoria) REFERENCES TBLPROCAT(id);

ALTER TABLE TBLUSU 
ADD CONSTRAINT FK_USUARIOPERFIL FOREIGN KEY(id_perfil) REFERENCES TBLUSUPER(id);

--ALTER TABLE PARA ADICIONAR PK COMPOSTA

ALTER TABLE TBLVEN DROP CONSTRAINT FK_CLIENTEVENDA;

ALTER TABLE TBLCLI 
DROP CONSTRAINT PK_CLIENTE,
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(id, cpf, cnpj);

ALTER TABLE TBLVEN 
ADD CONSTRAINT FK_CLIENTEVENDA FOREIGN KEY(id_cliente, cpf_cliente, cnpj_cliente) REFERENCES TBLCLI(id, cpf, cnpj);

ALTER TABLE TBLCOM DROP CONSTRAINT FK_FORNECEDORCOMPRA;

ALTER TABLE TBLFOR
DROP CONSTRAINT PK_FORNECEDOR,
ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY(id, cnpj);

ALTER TABLE TBLCOM
ADD CONSTRAINT FK_FORNECEDORCOMPRA FOREIGN KEY(id_fornecedor, cnpj_fornecedor) REFERENCES TBLFOR(id, cnpj);

--TRIGGER AUTO INCREMENT

CREATE SEQUENCE ID_TBLCLI;
CREATE SEQUENCE ID_TBLCOM;
CREATE SEQUENCE ID_TBLFOR;
CREATE SEQUENCE ID_TBLPRO;
CREATE SEQUENCE ID_TBLPROCAT;
CREATE SEQUENCE ID_TBLUSU;
CREATE SEQUENCE ID_TBLUSUPER;
CREATE SEQUENCE ID_TBLVEN;

SET TERM !! ;

CREATE TRIGGER TBLCLI_AUTOINCREMENT FOR TBLCLI
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLCLI;
END!!

CREATE TRIGGER TBLCOM_AUTOINCREMENT FOR TBLCOM
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLCOM;
END!!

CREATE TRIGGER TBLPRO_AUTOINCREMENT FOR TBLPRO
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLPRO;
END!!

CREATE TRIGGER TBLFOR_AUTOINCREMENT FOR TBLFOR
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLFOR;
END!!

CREATE TRIGGER TBLPROCAT_AUTOINCREMENT FOR TBLPROCAT
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLPROCAT;
END!!

CREATE TRIGGER TBLUSU_AUTOINCREMENT FOR TBLUSU
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLUSU;
END!!

CREATE TRIGGER TBLUSUPER_AUTOINCREMENT FOR TBLUSUPER
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLUSUPER;
END!!

CREATE TRIGGER TBLVEN_AUTOINCREMENT FOR TBLVEN
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
	if (NEW.id is NULL) then NEW.id = NEXT VALUE FOR ID_TBLVEN;
END!!

SET TERM ; !!