--TABELA CLIENTE
CREATE TABLE TBLCLI (
	id INTEGER NOT NULL PRIMARY KEY,
	nome VARCHAR(100),
	cpf VARCHAR(20),
	cnpj VARCHAR(30),
	data_nascimento DATE,
	ativo BOOLEAN
);

--TABELA PRODUTO CATEGORIA
CREATE TABLE TBLPROCAT (
	id INTEGER NOT NULL PRIMARY KEY,
	categoria VARCHAR(50)
);

--TABELA PRODUTO
CREATE TABLE TBLPRO (
	id INTEGER NOT NULL PRIMARY KEY,
	nome VARCHAR(100),
	descricao VARCHAR(255),
	quantidade INTEGER,
	preco_custo DOUBLE PRECISION,
	preco_venda DOUBLE PRECISION,
	id_categoria INTEGER REFERENCES TBLPROCAT,
	ativo BOOLEAN
);

--TABELA USUARIOS PERFIL
CREATE TABLE TBLUSUPER (
	id INTEGER NOT NULL PRIMARY KEY,
	perfil VARCHAR(20)
);

--TABELA USUARIOS
CREATE TABLE TBLUSU (
	id INTEGER NOT NULL PRIMARY KEY,
	nome VARCHAR(100),
	matricula VARCHAR(20),
	data_contratacao DATE,
	id_perfil INTEGER REFERENCES TBLUSUPER,
	ativo BOOLEAN
);

--TABELA VENDAS
CREATE TABLE TBLVEN (
	id INTEGER NOT NULL PRIMARY KEY,
	id_cliente INTEGER REFERENCES TBLCLI,
	id_vendedor INTEGER REFERENCES TBLUSU,
	id_produto INTEGER REFERENCES TBLPRO
);